### ISSUE TITLE
[tck][webcontainer] BundleManifestHeadersTest#testManifestHeaders015 should not treat wm3tw5.war as a bundle

### ISSUE THREAD

**Issue by grgrzybek** [osgi/osgi#578]
https://github.com/osgi/osgi/blob/d38340f72c4770b601d6b7fe04dd60954c636735/org.osgi.test.cases.webcontainer/src/org/osgi/test/cases/webcontainer/junit/BundleManifestHeadersTest.java#L176-L189 test:

fails with Pax Web / Pax URL by not failing to install the bundle. The test (IMO) wrongly assumes that `wm3tw5.war` is a bundle, but it contains only these headers:
```
Manifest-Version: 1.0
Bundle-Description: OSGi Web Container RFC 66 Compliance Test test war
  5 with manifest Bundle-Classpath pre-specified
Bundle-Name: org.osgi.test.cases.webcontainer.wm3tw5
Bundle-Vendor: Eclipse Foundation
```

However [128.4.4 WAB Modification](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.war.html#d0e70497) says:
> The Web URL Handler can set or modify the Web-ContextPath of a WAB if the input source is already a bundle. It must be considered as a bundle when any of the OSGi defined headers listed in [Table 128.3](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.war.html#service.war-webbundle.url.parameters) is present in the bundle.
>
> WAB Modification, the Web URL Handler must only support the Web-ContextPath parameter and it must not modify any existing headers other than the Web-ContextPath. Any other parameter given must result in a Bundle Exception.

The table however mentions only these attributes:
* Bundle-SymbolicName
* Bundle-Version
* Bundle-ManifestVersion
* Import-Package
* Web-ContextPath

So (IMO) `wm3tw5.war` should not be _considered as a bundle_.

**Comment by grgrzybek** [comment]
Again, the comment is misleading. This bundle contains:
```
Manifest-Version: 1.0
Bundle-Description: OSGi Web Container RFC 66 Compliance Test test war
  5 with manifest Bundle-Classpath pre-specified
Bundle-Name: org.osgi.test.cases.webcontainer.wm3tw5
Bundle-Vendor: Eclipse Foundation
```

So according to [128.4.4 WAB Modification](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.war.html#d0e70497), this is NOT a bundle.

The exception is:
```
org.osgi.framework.BundleException: Error reading bundle content.
	at org.eclipse.osgi.storage.Storage.install(Storage.java:678)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:182)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:175)
	at org.osgi.test.cases.webcontainer.util.WebContainerTestBundleControl.installBundle(WebContainerTestBundleControl.java:456)
	at org.osgi.test.cases.webcontainer.util.WebContainerTestBundleControl.installBundle(WebContainerTestBundleControl.java:477)
	at org.osgi.test.cases.webcontainer.util.WebContainerTestBundleControl.installWar(WebContainerTestBundleControl.java:119)
	at org.osgi.test.cases.webcontainer.junit.BundleManifestHeadersTest.testManifestHeaders015(BundleManifestHeadersTest.java:183)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at aQute.tester.bundle.engine.BundleDescriptor.executeChild(BundleDescriptor.java:49)
	at aQute.tester.bundle.engine.BundleEngine.lambda$executeBundle$7(BundleEngine.java:120)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at aQute.tester.bundle.engine.BundleEngine.executeBundle(BundleEngine.java:120)
	at aQute.tester.bundle.engine.BundleEngine.lambda$execute$5(BundleEngine.java:100)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at aQute.tester.bundle.engine.BundleEngine.execute(BundleEngine.java:100)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at aQute.tester.junit.platform.Activator.test(Activator.java:441)
	at aQute.tester.junit.platform.Activator.automatic(Activator.java:345)
	at aQute.tester.junit.platform.Activator.run(Activator.java:217)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at aQute.launcher.Launcher.handleMainCallable(Launcher.java:465)
	at aQute.launcher.Launcher.launch(Launcher.java:438)
	at aQute.launcher.Launcher.run(Launcher.java:186)
	at aQute.launcher.Launcher.main(Launcher.java:162)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
Caused by: java.lang.IllegalArgumentException: Web-ContextPath is missing
	at org.eclipse.gemini.web.internal.url.SpecificationWebBundleManifestTransformer.transformWebContextPath(SpecificationWebBundleManifestTransformer.java:192)
	at org.eclipse.gemini.web.internal.url.SpecificationWebBundleManifestTransformer.transform(SpecificationWebBundleManifestTransformer.java:58)
	at org.eclipse.gemini.web.internal.url.ChainingWebBundleManifestTransformer.transform(ChainingWebBundleManifestTransformer.java:41)
	at org.eclipse.gemini.web.internal.url.WebBundleUrlStreamHandlerService$Callback.transformManifest(WebBundleUrlStreamHandlerService.java:120)
	at org.eclipse.gemini.web.internal.url.WebBundleUrlStreamHandlerService$Callback.transformEntry(WebBundleUrlStreamHandlerService.java:102)
	at org.eclipse.virgo.util.io.JarTransformer.transformEntry(JarTransformer.java:107)
	at org.eclipse.virgo.util.io.JarTransformer.transform(JarTransformer.java:82)
	at org.eclipse.virgo.util.io.JarTransformingURLConnection.getInputStream(JarTransformingURLConnection.java:66)
	at org.eclipse.osgi.storage.Storage.install(Storage.java:676)
	... 70 more
```

Pax URL didn't check if the `Web-ContextPath` is configured for non-bundle WAR. This is fixed with ops4j/org.ops4j.pax.url#419.
