### ISSUE TITLE
Named Pushstreams and Eventsources

### ISSUE THREAD

**Issue by juergen-albert** [osgi/osgi#777]
If something fails in a Pushstream or Eventsource e.g. a Queue is full, it is often hard to find the offending stream due to the async nature, because the only thing you might find in you logs is:

```
java.lang.IllegalStateException: Queue full
	at java.base/java.util.AbstractQueue.add(Unknown Source)
	at java.base/java.util.concurrent.ArrayBlockingQueue.add(Unknown Source)
	at org.osgi.util.pushstream.QueuePolicyOption$3.lambda$getPolicy$0(QueuePolicyOption.java:69)
	at org.osgi.util.pushstream.BufferedPushStreamImpl.handleEvent(BufferedPushStreamImpl.java:75)
	at org.osgi.util.pushstream.SimplePushEventSourceImpl.safePush(SimplePushEventSourceImpl.java:151)
	at org.osgi.util.pushstream.SimplePushEventSourceImpl.doCall(SimplePushEventSourceImpl.java:362)
	at org.osgi.util.pushstream.SimplePushEventSourceImpl.deliver(SimplePushEventSourceImpl.java:343)
	at org.osgi.util.pushstream.SimplePushEventSourceImpl.lambda$startWorker$6(SimplePushEventSourceImpl.java:283)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Thus it might be great, if we could give Pushstreams and Eventsources names, so they can be used in Exceptions.

**Comment by stbischof** [comment]
Please come with an update on the spec
