### ISSUE TITLE
DS: Coercing Component Property Values: String -> Long 

### ISSUE THREAD

**Issue by joerghoh** [osgi/osgi#794]
Currently the coercion rules mandate that the conversion from String to Long is done via ``Long.parseLong(String)``, but this method cannot parse the exponential notation of Long values.

```
The activate method has thrown an exception (org.apache.felix.log.LogException: org.osgi.service.component.ComponentException: java.lang.NumberFormatException: For input string: "1.2e+07")
org.apache.felix.log.LogException: org.osgi.service.component.ComponentException: java.lang.NumberFormatException: For input string: "1.2e+07"
	at org.apache.felix.scr.impl.inject.internal.Annotations$Handler.invoke(Annotations.java:379) [org.apache.felix.scr:2.2.12]
	at my.own.$Proxy193.aLongProperty(Unknown Source) [mybundle]
	at my.own.component.activate(component.java:229) [mybundle]
```

**Comment by laeubi** [comment]
If I try

`long x = 1.2e+07;`

my java compiler complains that it is invalid.

Also https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Long.html does not give a hin that there is actually something like an "exponential notation of Long values"

**Comment by stbischof** [comment]
could you please add a test to the tck?

**Comment by timothyjward** [comment]
> could you please add a test to the tck?
> 

I'm not sure what test is being added here. I'm not aware of there being exponential support in any of the base types representing natural numbers. There is support in [`BigDecimal`](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#BigDecimal-java.lang.String-) and [`Double`](https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#valueOf-java.lang.String-) but both of these are handled in the existing conversion methods.

**Comment by laeubi** [comment]
> could you please add a test to the tck?

I think first there needs to be agreement and a spec change before changing tests....
